package com.web.hulklogic.utility;

public enum StatusEnum {

	EMAIL_EXISTED, PHONE_NUMBER_EXISTED, SUCCESS, FAIL, NOUSER, DISABLE, TEMPLATENAME_EXISTED, NO_SIGNATURE, FILE_NAME_NOT_EXISTED, JOBASSING_ANOTHER_RECRUITER

}
